#upstream_project_url: https://github.com/dustymabe/trash-vagrant-sshfs-packit-source-git

# The upstream_ref is the last upstream commit. All commits in the
# current branch after that commit are "patches" that will be added
# in the RPM spec file.
upstream_ref: v1.3.1

upstream_package_name: vagrant-sshfs
downstream_package_name: vagrant-sshfs
specfile_path: vagrant-sshfs.spec
synced_files:
  - vagrant-sshfs.spec
create_pr: true # Don't push to dist-git, create PR
# our tags in git are v1.0.0 and our rpm versions are 1.0.0
upstream_tag_template: v{version}
####jobs:
####- job: sync_from_downstream
####  trigger: commit
####- job: propose_downstream
####  trigger: commit
####  metadata:
####    dist-git-branch: master
####- job: propose_downstream
####  trigger: release
####  metadata:
####    dist-git-branch: f31
####- job: copr_build
####  trigger: pull_request
####  metadata:
####    targets:
####    - fedora-31-x86_64
